Config={}
Config.Locale='fr'

Config.WeaponList = {
  'GADGET_PARACHUTE',
  'WEAPON_PETROLCAN',
  'WEAPON_FIREEXTINGUISHER',
  'WEAPON_MOLOTOV',
  'WEAPON_BZGAS',
  'WEAPON_FLASHLIGHT',
  'WEAPON_KNIFE',
  'WEAPON_HAMMER',
  'WEAPON_CROWBAR',
  'WEAPON_BAT',
  'WEAPON_POOLCUE',
  'WEAPON_GOLFCLUB',
  'WEAPON_HATCHET',
  'WEAPON_MACHETE',
  'WEAPON_KNUCKLE',
  'WEAPON_SWITCHBLADE',
  'WEAPON_NIGHTSTICK',
  'WEAPON_FLAREGUN',
  'WEAPON_STUNGUN',
  'WEAPON_SNSPISTOL',
  'WEAPON_COMBATPISTOL',
  'WEAPON_REVOLVER',
  'WEAPON_HEAVYPISTOL',
  'WEAPON_PISTOL_MK2',
  'WEAPON_MUSKET',
  'WEAPON_DBSHOTGUN',
  'WEAPON_SAWNOFFSHOTGUN',
  'WEAPON_SMG',
  'WEAPON_SMG_MK2',
  'WEAPON_BULLPUPSHOTGUN',
  'WEAPON_ASSAULTSMG',
  'WEAPON_ASSAULTRIFLE',
  'WEAPON_MARKSMANRIFLE'
}

Config.ComponentList = {
  'COMPONENT_AT_PI_FLSH',
  'COMPONENT_AT_AR_FLSH',
  'COMPONENT_AT_AR_AFGRIP',
  'COMPONENT_AT_SCOPE_MACRO',
  'COMPONENT_AT_PI_SUPP',
  'COMPONENT_AT_AR_SUPP_02',
  'COMPONENT_AT_PI_CLIP_02',
  'COMPONENT_AT_AR_CLIP_02',
  'COMPONENT_AT_AR_CLIP_03',
  'COMPONENT_AT_PI_COMP',
  'COMPONENT_AT_PI_RAIL',
  'COMPONENT_VARMOD_LOWRIDER',        
  'COMPONENT_VARMOD_LUXE',
  'COMPONENT_KNUCKLE_VARMOD_PLAYER',
  'COMPONENT_KNUCKLE_VARMOD_LOVE',
  'COMPONENT_KNUCKLE_VARMOD_DOLLAR',
  'COMPONENT_KNUCKLE_VARMOD_VAGOS',
  'COMPONENT_KNUCKLE_VARMOD_HATE',
  'COMPONENT_KNUCKLE_VARMOD_DIAMOND',
  'COMPONENT_KNUCKLE_VARMOD_PIMP',
  'COMPONENT_KNUCKLE_VARMOD_KING',
  'COMPONENT_KNUCKLE_VARMOD_BALLAS',
  'COMPONENT_SWITCHBLADE_VARMOD_VAR1',
  'COMPONENT_SWITCHBLADE_VARMOD_VAR2',
  'COMPONENT_REVOLVER_VARMOD_BOSS',
  'COMPONENT_REVOLVER_VARMOD_GOON',
  'COMPONENT_MK2_CAMO',
  'COMPONENT_MK2_CAMO_02',
  'COMPONENT_MK2_CAMO_03',
  'COMPONENT_MK2_CAMO_04',
  'COMPONENT_MK2_CAMO_05',
  'COMPONENT_MK2_CAMO_06',
  'COMPONENT_MK2_CAMO_07',
  'COMPONENT_MK2_CAMO_08',
  'COMPONENT_MK2_CAMO_09',
  'COMPONENT_MK2_CAMO_10',
  'COMPONENT_MK2_CAMO_IND_01'
}

Config.CamoList = {
  'COMPONENT_PISTOL_MK2_CLIP_02',
  'COMPONENT_PISTOL_MK2_CAMO',
  'COMPONENT_PISTOL_MK2_CAMO_02',
  'COMPONENT_PISTOL_MK2_CAMO_03',
  'COMPONENT_PISTOL_MK2_CAMO_04',
  'COMPONENT_PISTOL_MK2_CAMO_05',
  'COMPONENT_PISTOL_MK2_CAMO_06',
  'COMPONENT_PISTOL_MK2_CAMO_07',
  'COMPONENT_PISTOL_MK2_CAMO_08',
  'COMPONENT_PISTOL_MK2_CAMO_09',
  'COMPONENT_PISTOL_MK2_CAMO_10',
  'COMPONENT_PISTOL_MK2_CAMO_IND_01',
  'COMPONENT_SMG_MK2_CAMO',
  'COMPONENT_SMG_MK2_CAMO_02',
  'COMPONENT_SMG_MK2_CAMO_03',
  'COMPONENT_SMG_MK2_CAMO_04',
  'COMPONENT_SMG_MK2_CAMO_05',
  'COMPONENT_SMG_MK2_CAMO_06',
  'COMPONENT_SMG_MK2_CAMO_07',
  'COMPONENT_SMG_MK2_CAMO_08',
  'COMPONENT_SMG_MK2_CAMO_09',
  'COMPONENT_SMG_MK2_CAMO_10',
  'COMPONENT_SMG_MK2_CAMO_IND_01',
  'COMPONENT_AT_SCOPE_SMALL_SMG_MK2'
}

Config.WeaponsComponentsList = {
  WEAPON_PISTOL_MK2 = {
    flashlight  = 'COMPONENT_AT_PI_FLSH_02',
    suppressorP = 'COMPONENT_AT_PI_SUPP_02',
    clipP       = 'COMPONENT_PISTOL_MK2_CLIP_02',
    cam_01      = 'COMPONENT_PISTOL_MK2_CAMO',
    cam_02      = 'COMPONENT_PISTOL_MK2_CAMO_02',
    cam_03      = 'COMPONENT_PISTOL_MK2_CAMO_03',
    cam_04      = 'COMPONENT_PISTOL_MK2_CAMO_04',
    cam_05      = 'COMPONENT_PISTOL_MK2_CAMO_05',
    cam_06      = 'COMPONENT_PISTOL_MK2_CAMO_06',
    cam_07      = 'COMPONENT_PISTOL_MK2_CAMO_07',
    cam_08      = 'COMPONENT_PISTOL_MK2_CAMO_08',
    cam_09      = 'COMPONENT_PISTOL_MK2_CAMO_09',
    cam_10      = 'COMPONENT_PISTOL_MK2_CAMO_10',
    cam_11      = 'COMPONENT_PISTOL_MK2_CAMO_IND_01'
  },
  WEAPON_SMG_MK2 = {
    flashlight  = 'COMPONENT_AT_PI_FLSH_02',
    suppressorR = 'COMPONENT_AT_PI_SUPP',
    clipR       = 'COMPONENT_SMG_MK2_CLIP_02',
    cam_01      = 'COMPONENT_SMG_MK2_CAMO',
    cam_02      = 'COMPONENT_SMG_MK2_CAMO_02',
    cam_03      = 'COMPONENT_SMG_MK2_CAMO_03',
    cam_04      = 'COMPONENT_SMG_MK2_CAMO_04',
    cam_05      = 'COMPONENT_SMG_MK2_CAMO_05',
    cam_06      = 'COMPONENT_SMG_MK2_CAMO_06',
    cam_07      = 'COMPONENT_SMG_MK2_CAMO_07',
    cam_08      = 'COMPONENT_SMG_MK2_CAMO_08',
    cam_09      = 'COMPONENT_SMG_MK2_CAMO_09',
    cam_10      = 'COMPONENT_SMG_MK2_CAMO_10',
    cam_11      = 'COMPONENT_SMG_MK2_CAMO_IND_01',
    scope       = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2'
  },
  WEAPON_ASSAULTSMG = {
    clipR       = 'COMPONENT_ASSAULTSMG_CLIP_02',
    lowrider    = 'COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER'
  },
  WEAPON_ASSAULTRIFLE = {
    clipR       = 'COMPONENT_ASSAULTRIFLE_CLIP_02',
    clipR2      = 'COMPONENT_ASSAULTRIFLE_CLIP_03',
    luxe        = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE'
  },
  WEAPON_SMG = {
    suppressorR = 'COMPONENT_AT_PI_SUPP',
    clipR       = 'COMPONENT_SMG_CLIP_02',
    clipR2      = 'COMPONENT_SMG_CLIP_03',
    scope       = 'COMPONENT_AT_SCOPE_MACRO_02',
    luxe        = 'COMPONENT_SMG_VARMOD_LUXE'
  },
  WEAPON_SNSPISTOL = {
    clipP       = 'COMPONENT_SNSPISTOL_CLIP_02',
    lowrider    = 'COMPONENT_SNSPISTOL_VARMOD_LOWRIDER'
  },
  WEAPON_COMBATPISTOL = {
    clipP       = 'COMPONENT_COMBATPISTOL_CLIP_02',
    lowrider    = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER'
  },
  WEAPON_HEAVYPISTOL = {
    clipP       = 'COMPONENT_HEAVYPISTOL_CLIP_02',
    luxe        = 'COMPONENT_HEAVYPISTOL_VARMOD_LUXE'
  },
  WEAPON_SAWNOFFSHOTGUN = {
    luxe        = 'COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE'
  },
  WEAPON_MARKSMANRIFLE = {
    clipR       = 'COMPONENT_MARKSMANRIFLE_CLIP_02',
    suppressorR = 'COMPONENT_AT_AR_SUPP'
  }
}
