---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:36
---
UITimerBarPool = setmetatable({}, UITimerBarPool)
UITimerBarPool.__index = UITimerBarPool

---New
---@return table
---@public
function UITimerBarPool.New()
    local _UITimerBarPool = {
        TimerBars = {},
    }
    return setmetatable(_UITimerBarPool, UITimerBarPool)
end

---Add
---@param TimerBar table
---@return table
---@public
function UITimerBarPool:Add(TimerBar)
    if TimerBar() == "UITimerBarProgressItem" or "UITimerBarItem" then
        table.insert(self.TimerBars, TimerBar)
        return #self.TimerBars
    end
end

---Remove
---@param id number
---@return number
---@public
function UITimerBarPool:Remove(id)
    table.remove(self.TimerBars, id)
    return self.TimerBars
end

---Draw
---@return nil
---@public
function UITimerBarPool:Draw()
    for _, TimerBar in pairs(self.TimerBars) do
        TimerBar:Draw(38 * _)
    end
    if (#self.TimerBars > 0) then
        for i = 6, 9, 1 do
            HideHudComponentThisFrame(i)
        end
    end
end

